version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend/gigflow-frontend
    ports:
      - "80:80"
    depends_on:
      - backend